name: flutter_paytorl
description: A Flutter library for handling Payto Resource Locators (PRLs). Based on the URL API and provides additional functionality for managing PRLs.
version: 0.1.2
homepage: https://github.com/bchainhub/flutter_paytorl
repository: https://github.com/bchainhub/flutter_paytorl
documentation: https://github.com/bchainhub/flutter_paytorl#readme
issue_tracker: https://github.com/bchainhub/flutter_paytorl/issues

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=3.29.1"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# Keywords related to the package
topics:
  - payto
  - payment
  - url
  - resource-locator
  - finance

# Funding links
funding:
  - https://github.com/sponsors/bchainhub
  - https://blockindex.net/address/cb7147879011ea207df5b35a24ca6f0859dcfb145999

# Platform support
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
